# Generated by Django 6.0.6 on 2026-07-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('fund_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('office_section', models.CharField(blank=True, max_length=255, null=True)),
                ('pr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('responsibility_center_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('funds_available_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('twg_verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_property_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('item_description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.purchaserequest')),
            ],
        ),
    ]
