# Generated by Django 6.0.6 on 2026-07-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quotation_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='quotation',
            name='unique_supplier_pr_quotation',
        ),
        migrations.AddField(
            model_name='supplier',
            name='products_services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(default='Pending Review', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('supplier', 'purchase_request')},
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_categories', to='api.category'),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_categories', to='api.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('supplier', 'category')},
        ),
    ]
