# Generated by Django 6.0.6 on 2026-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_suppliercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='review_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='verification_status',
            field=models.CharField(default='Pending', max_length=32),
        ),
    ]
