# Generated by Django 6.0.6 on 2026-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notification_related_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='abc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rfq',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='mode_of_procurement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rfq',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rfq',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
