# Generated by Django 6.0.6 on 2026-09-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rfq_abc_rfq_additional_notes_rfq_mode_of_procurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='award_basis',
            field=models.CharField(choices=[('LOT', 'By Lot'), ('UNIT', 'By Unit')], default='LOT', max_length=10),
        ),
    ]
