# Generated by Django 6.0.6 on 2026-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rfq_award_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='submitted_pdf',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
