# Generated by Django 6.0.6 on 2026-09-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_purchaserequest_declaration_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='delivery_method',
            field=models.CharField(choices=[('system', 'System'), ('manual', 'Manual')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='rfq',
            name='manual_supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='api.supplier'),
        ),
    ]
