# Generated by Django 6.0.6 on 2026-09-10 02:23

import django.db.models.deletion
from django.db import migrations, models


def backfill_rfq_items(apps, schema_editor):
    """Existing RFQs covered every item on their PR - record that explicitly so
    the new ``rfq_items``-based item selection matches historical behaviour."""
    RFQ = apps.get_model('api', 'RFQ')
    RFQItem = apps.get_model('api', 'RFQItem')
    PurchaseRequestItem = apps.get_model('api', 'PurchaseRequestItem')

    rows = []
    for rfq in RFQ.objects.all().iterator():
        for item_id in PurchaseRequestItem.objects.filter(
            purchase_request_id=rfq.purchase_request_id
        ).values_list('id', flat=True):
            rows.append(RFQItem(rfq_id=rfq.id, purchase_request_item_id=item_id))
    if rows:
        RFQItem.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rfq_delivery_method_rfq_manual_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='api.category'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='rfq_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('supplier', 'purchase_request', 'rfq')},
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='api.purchaserequestitem')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='api.rfq')),
            ],
            options={
                'unique_together': {('rfq', 'purchase_request_item')},
            },
        ),
        migrations.RunPython(backfill_rfq_items, noop_reverse),
    ]
