# Generated by Django 6.0.6 on 2026-09-12 11:24

from django.db import migrations, models


# Matches the hardcoded numbering behavior this model replaces exactly:
# ``f'{today:%Y-%m}-{highest + 1:03d}'`` with the running count carrying over
# across months within the same year (see
# PurchaseRequestNumberTests.test_continues_sequence_for_new_month /
# test_resets_for_new_year in api/tests/test_supplier_registration.py) - i.e.
# a yearly reset, not a monthly one, even though the printed number's date
# portion changes every month.
DEFAULT_PR_NUMBER_FORMAT = {
    'prefix': '',
    'date_granularity': 'year_month',
    'separator': '-',
    'sequence_digits': 3,
    'reset_period': 'yearly',
}


def seed_default_format(apps, schema_editor):
    format_model = apps.get_model('api', 'PRNumberFormat')
    format_model.objects.get_or_create(key='global', defaults=DEFAULT_PR_NUMBER_FORMAT)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_award_basis_to_quotation_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNumberFormat',
            fields=[
                ('key', models.CharField(default='global', max_length=20, primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('date_granularity', models.CharField(choices=[('none', 'No date'), ('year', 'Year only (YYYY)'), ('year_month', 'Year and month (YYYY-MM)')], default='year_month', max_length=12)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('sequence_digits', models.PositiveSmallIntegerField(default=3)),
                ('reset_period', models.CharField(choices=[('never', 'Never (accumulate forever)'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_default_format, migrations.RunPython.noop),
    ]
