# Generated by Django 6.0.6 on 2026-09-12 12:19

from django.db import migrations, models


# Reproduces today's unconditional-notify behavior exactly: every status
# transition (except reaching 'uploaded', which isn't a toggleable
# transition) emails the submitter, and the automatic matched/in_review flip
# in pr_items_assign_categories is not muted. Nothing changes for an existing
# deployment until an admin edits these settings.
DEFAULT_PR_NOTIFICATION_SETTINGS = {
    'enabled': True,
    'notify_in_review': True,
    'notify_matched': True,
    'notify_approved': True,
    'notify_rejected': True,
    'mute_automatic_transitions': False,
}


def seed_default_settings(apps, schema_editor):
    settings_model = apps.get_model('api', 'PRNotificationSettings')
    settings_model.objects.get_or_create(key='global', defaults=DEFAULT_PR_NOTIFICATION_SETTINGS)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_pr_number_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNotificationSettings',
            fields=[
                ('key', models.CharField(default='global', max_length=20, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notify_in_review', models.BooleanField(default=True)),
                ('notify_matched', models.BooleanField(default=True)),
                ('notify_approved', models.BooleanField(default=True)),
                ('notify_rejected', models.BooleanField(default=True)),
                ('mute_automatic_transitions', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_default_settings, migrations.RunPython.noop),
    ]
