INSERT IGNORE INTO api_category (name, description, is_active) VALUES
('Advertising Agency Services','Advertising Agency Services',1),
('Agricultural Chemicals','Agricultural Chemicals',1),
('Agricultural Machinery and Equipment','Agricultural Machinery and Equipment',1),
('Agricultural Products (Seeds, Seedlings, Plants..)','Agricultural Products (Seeds, Seedlings, Plants..)',1),
('Airconditioning and Airconditioning Systems','Airconditioning and Airconditioning Systems',1),
('Airconditioning Maintenance Services','Airconditioning Maintenance Services',1),
('Aircraft Spare Parts','Aircraft Spare Parts',1),
('Ammunitions and Explosives','Ammunitions and Explosives',1),
('Animal Feeds','Animal Feeds',1),
('Appliances','Appliances',1),
('Architectural Design','Architectural Design',1),
('Arts and Crafts Accessories and Supplies','Arts and Crafts Accessories and Supplies',1),
('Audio and Visual Equipment','Audio and Visual Equipment',1),
('Automation Equipment','Automation Equipment',1),
('Aviation Products','Aviation Products',1),
('Aviation Services','Aviation Services',1),
('Bedclothes, Linens and Towels','Bedclothes, Linens and Towels',1),
('Beverages','Beverages',1),
('Books, Maps and Other Publications','Books, Maps and Other Publications',1),
('Cargo Forwarding and Hauling Services','Cargo Forwarding and Hauling Services',1),
('Catering Services','Catering Services',1),
('Chemical Detergents','Chemical Detergents',1),
('Chemicals and Chemical Products','Chemicals and Chemical Products',1),
('Communication Equipment','Communication Equipment',1),
('Communication Equipment & Parts and Accessories','Communication Equipment & Parts and Accessories',1),
('Computer Furniture','Computer Furniture',1),
('Construction Equipment','Construction Equipment',1),
('Construction Management Services','Construction Management Services',1),
('Construction Materials and Supplies','Construction Materials and Supplies',1),
('Construction Projects','Construction Projects',1),
('Consulting Services','Consulting Services',1),
('Corporate Giveaways','Corporate Giveaways',1),
('Dairy Products','Dairy Products',1),
('Diagnostic and Laboratory Services','Diagnostic and Laboratory Services',1),
('Drugs and Medicines','Drugs and Medicines',1),
('Editorial, Design, Graphic and Fine Art Services','Editorial, Design, Graphic and Fine Art Services',1),
('Educational Materials and Supplies','Educational Materials and Supplies',1),
('Electrical Supplies','Electrical Supplies',1),
('Electrical Systems and Lighting Components','Electrical Systems and Lighting Components',1),
('Electronic Parts and Components','Electronic Parts and Components',1),
('Engineering and Laboratory Testing Equipment','Engineering and Laboratory Testing Equipment',1),
('Environmental Health/Safety Equipment','Environmental Health/Safety Equipment',1),
('Events Management','Events Management',1),
('Fertilizers','Fertilizers',1),
('Fire Fighting & Rescue and Safety Equipment','Fire Fighting & Rescue and Safety Equipment',1),
('Fixtures','Fixtures',1),
('Flags','Flags',1),
('Food Processing Equipment','Food Processing Equipment',1),
('Food Stuff','Food Stuff',1),
('Freight Forwarder Services','Freight Forwarder Services',1),
('Fuels/Fuel Additives & Lubricants & Anti Corrosive','Fuels/Fuel Additives & Lubricants & Anti Corrosive',1),
('Furniture','Furniture',1),
('Furniture Parts and Accessories','Furniture Parts and Accessories',1),
('Games and Toys','Games and Toys',1),
('Gaming Equipment and Paraphernalia','Gaming Equipment and Paraphernalia',1),
('Garments','Garments',1),
('General Contractor','General Contractor',1),
('General Engineering Services','General Engineering Services',1),
('General Merchandise','General Merchandise',1),
('General Repair and Maintenance Services','General Repair and Maintenance Services',1),
('Geotechnical Instrumentation','Geotechnical Instrumentation',1),
('Grocery Items','Grocery Items',1),
('Guns and Weapons','Guns and Weapons',1),
('Hardware and Construction Supplies','Hardware and Construction Supplies',1),
('Helicopters - Parts','Helicopters - Parts',1),
('Horizontal Directional Drilling','Horizontal Directional Drilling',1),
('Hospital / Medical Equipment','Hospital / Medical Equipment',1),
('Hospital / Medical Equipment Services','Hospital / Medical Equipment Services',1),
('Hotel and Lodging and Meeting Facilities','Hotel and Lodging and Meeting Facilities',1),
('Hydrological Instruments','Hydrological Instruments',1),
('Industrial Machinery and Equipment','Industrial Machinery and Equipment',1),
('Industrial pumps and compressors','Industrial pumps and compressors',1),
('Industrial Safety Equipment','Industrial Safety Equipment',1),
('Information Technology','Information Technology',1),
('Information Technology Parts & Peripheral','Information Technology Parts & Peripheral',1),
('Institutional food services equipment','Institutional food services equipment',1),
('Internet Services','Internet Services',1),
('Investigative Equipment','Investigative Equipment',1),
('IT Broadcasting and Telecommunications','IT Broadcasting and Telecommunications',1),
('Janitorial Equipment','Janitorial Equipment',1),
('Janitorial Services','Janitorial Services',1),
('Janitorial Supplies','Janitorial Supplies',1),
('Kitchenware','Kitchenware',1),
('Laboratory Supplies and Equipment','Laboratory Supplies and Equipment',1),
('Laundry Services','Laundry Services',1),
('Lease and Rental of Property or Building','Lease and Rental of Property or Building',1),
('Lifting equipment and accessories','Lifting equipment and accessories',1),
('Live Animals (Livestock, Birds, Live fish & etc..)','Live Animals (Livestock, Birds, Live fish & etc..)',1),
('Machine Tools','Machine Tools',1),
('Mail and Cargo Transport Services','Mail and Cargo Transport Services',1),
('Mailing Supplies','Mailing Supplies',1),
('Marine Transport','Marine Transport',1),
('Maritime Spare Parts','Maritime Spare Parts',1),
('Market Research Services','Market Research Services',1),
('Medical and Dental Equipment','Medical and Dental Equipment',1),
('Medical Supplies and Laboratory Instrument','Medical Supplies and Laboratory Instrument',1),
('Metal Fabrication','Metal Fabrication',1),
('Meteorological Equipments and Instruments','Meteorological Equipments and Instruments',1),
('Microfilm Equipment','Microfilm Equipment',1),
('Microfilm Equipment - Supplies and Accesories','Microfilm Equipment - Supplies and Accesories',1),
('Mining Equipment and Supplies','Mining Equipment and Supplies',1),
('Musical Instrument Parts and Accesories','Musical Instrument Parts and Accesories',1),
('Musical Instruments','Musical Instruments',1),
('Navigation Equipment','Navigation Equipment',1),
('Newspapers','Newspapers',1),
('Office Equipment','Office Equipment',1),
('Office Equipment Parts and Accessories','Office Equipment Parts and Accessories',1),
('Office Equipment Supplies and Consumables','Office Equipment Supplies and Consumables',1),
('Office Supplies and Devices','Office Supplies and Devices',1),
('Oil/Heat Chemical Resistant Rubber','Oil/Heat Chemical Resistant Rubber',1),
('Ordnance Products','Ordnance Products',1),
('Packaging Supplies and Materials','Packaging Supplies and Materials',1),
('Personal Care Products','Personal Care Products',1),
('Pest Control Products','Pest Control Products',1),
('Pest Control Services','Pest Control Services',1),
('Photographic Equipment','Photographic Equipment',1),
('Photographic Parts, Supplies and Accessories','Photographic Parts, Supplies and Accessories',1),
('Photography Services','Photography Services',1),
('Plastic Products','Plastic Products',1),
('Power Generation and Distribution Machinery','Power Generation and Distribution Machinery',1),
('Preserved or Processed Foods','Preserved or Processed Foods',1),
('Print and Broadcast and Aerial Advertising','Print and Broadcast and Aerial Advertising',1),
('Printing Services','Printing Services',1),
('Printing Supplies','Printing Supplies',1),
('Public Relations Programs or Services','Public Relations Programs or Services',1),
('Purses, handbags and bags','Purses, handbags and bags',1),
('Pyrotechnics and Fireworks','Pyrotechnics and Fireworks',1),
('Quartermaster Items','Quartermaster Items',1),
('Radiological/Diagnostic Equipment','Radiological/Diagnostic Equipment',1),
('Real Estate Developement and Maintenance','Real Estate Developement and Maintenance',1),
('Reproduction Services','Reproduction Services',1),
('Rice Milling Services','Rice Milling Services',1),
('Safety and Occupational Products','Safety and Occupational Products',1),
('Sale of Property or Building','Sale of Property or Building',1),
('Security Services','Security Services',1),
('Security Surveillance and Detection Equipment','Security Surveillance and Detection Equipment',1),
('Services','Services',1),
('Signage and Accessories','Signage and Accessories',1),
('Sporting Goods','Sporting Goods',1),
('Structured Cabling','Structured Cabling',1),
('Sub-station Contractors','Sub-station Contractors',1),
('Surveying Instruments','Surveying Instruments',1),
('Surveying Services','Surveying Services',1),
('Systems Integration','Systems Integration',1),
('Telecommunications Engineering','Telecommunications Engineering',1),
('Telecommunications Provider','Telecommunications Provider',1),
('Textiles','Textiles',1),
('Timepieces and Jewelry and Gemstone Products','Timepieces and Jewelry and Gemstone Products',1),
('Tokens and Awards','Tokens and Awards',1),
('Traffic Control Systems','Traffic Control Systems',1),
('Transmission and Distribution Lines','Transmission and Distribution Lines',1),
('Transportation and Communications Services','Transportation and Communications Services',1),
('Travel, Food, Lodging and Entertainment Services','Travel, Food, Lodging and Entertainment Services',1),
('Vehicle Parts and Accessories','Vehicle Parts and Accessories',1),
('Vehicle Repair and Maintenance','Vehicle Repair and Maintenance',1),
('Vehicles','Vehicles',1),
('Veterinary Products and Supplies','Veterinary Products and Supplies',1),
('Video Production Services','Video Production Services',1),
('Waste Management and Recycling','Waste Management and Recycling',1),
('Water and Waste Water Treatment Supply & Disposal','Water and Waste Water Treatment Supply & Disposal',1),
('Water Service Connection Materials/Fittings','Water Service Connection Materials/Fittings',1),
('Well Drilling and Construction Services','Well Drilling and Construction Services',1);
